server:
  rootPath: /rest
  applicationConnectors:
  - type: http
    port: 8888
  - type: https
    port: 443
    keyStorePath: ./server/team-space-server/target/classes/keys/keystore.jks
    keyStorePassword: ts3passx!
    validateCerts: false
    validatePeers: false
  - type: https
    port: 8443
    keyStorePath: ./server/team-space-server/target/classes/keys/keystore.p12
    keyStorePassword: ts3passx!
    keyStoreType: PKCS12
    trustStoreType: PKCS12
    validateCerts: false
    validatePeers: false
  adminConnectors:
  - type: http
    port: 8889

logging:
  loggers:
    "org.teamspace": DEBUG
  appenders:
    - type: console
      threshold: DEBUG
      target: stdout
    - type: file
      currentLogFilename: ./logs/ts/teamspace.log
      archivedLogFilenamePattern: ./logs/ts/teamspace-%d{yyyy-MM-dd-HH}-%i.log.gz
      maxFileSize: 100MB
      threshold: DEBUG
    - type: file
      currentLogFilename: ./logs/ts/errors.log
      archivedLogFilenamePattern: ./logs/ts/errors-%d{yyyy-MM-dd-HH}-%i.log.gz
      maxFileSize: 100MB
      threshold: ERROR

